name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: Python${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.4.0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.3.2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python setup.py develop
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          flake8 --max-line-length=120 restructuredtext_lint
          nose2 restructuredtext_lint
